// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tndmfwjbpzwyxszjyfhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZG1md2picHp3eXhzemp5ZmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDYwNzEsImV4cCI6MjA2NTYyMjA3MX0.C2x78VkFarXSZarUYjMP6nXkM4YG1k9cBmZP-thVpq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);